repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-go
        args: [markdown, table, --output-file, pre-commit.md, ./]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_tfsec
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [
            chore,
            ci,
            docs,
            hotfix,
            bugfix,
            feat,
            feature,
            fix,
            perf,
            refactor,
            revert,
            test,
          ] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]